config/routes.rb
 PayUp::Application.routes.draw do


  resources :users
  resources :bets
  resource :userbet

<<<<<<< HEAD
  get '/users/bet' => 'venmo#home', as: :home
  post '/users/bet' => 'users#bet'
  

  
=======
  get '/settle/bet' => 'bets#settle'
>>>>>>> 621f83c2b1c13f326b9a39dcd2f413e9da282a43

  resource :session, only: [:new, :create, :destroy]



  root 'sessions#new'
  
end

app/models/bet.rb
class Bet < ActiveRecord::Base
  include Workflow
	workflow do
    state :pending do
      event :accept, :transitions_to => :accepted
      event :reject, :transitions_to => :rejected
    end
    state :accepted
    state :rejected
  end
 
  validates_presence_of :challenge, :amount, :winner_id, :is_accepted

  # belongs_to :beter, class_name: "User", foreign_key: :user_id, inverse_of: :beters

  # belongs_to :betee, class_name: "User", foreign_key: :betee_id, inverse_of: :betees

  has_many :user_bets
  has_many :users, through: :user_bets, :foreign_key => :user_id

  accepts_nested_attributes_for :users 
end 

app/models/user.rb
class User < ActiveRecord::Base

	# has_many :beters, class_name: "Bet", foreign_key: :user_id, inverse_of: :beter

 #  has_many :betees, class_name: "Bet", foreign_key: :betee_id, inverse_of: :betee

 	has_many :user_bets, :dependent => :destroy
 	has_many :bets, through: :user_bets, :foreign_key => :bet_id

 	accepts_nested_attributes_for :bets 
end
  

app/models/user_bet.rb
class UserBet < ActiveRecord::Base

  belongs_to :bet
  belongs_to :user
  
  accepts_nested_attributes_for :bet

end
  

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  
  helper_method :current_user 

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  	puts current_user
  end
  def current_id
  	@current_id ||= request.original_url
  	puts @current_id
  end
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController

	respond_to :json
  #respond back with json when performing crud function

  def settle
    

    if params["code"]
      auth_code = params["code"]
    end 
    url = "https://api.venmo.com/v1/oauth/access_token"
    @response = HTTParty.post(url, :query => {:client_id => '1916', :client_secret => 'eGcyNHaysfbFGZ6xkMffUw3gGrKFzksG', :code => auth_code})
    user = @response["user"]
    @access_token = @response["access_token"]
    @refresh_token = @response["refresh_token"]
    @email = params[:email]
    @amount = params[:amount]
   
    url = "https://api.venmo.com/v1/payments"
    @amount = HTTParty.post(url, :query => { "access_token" => @access_token, :email => @email, :amount => @amount, :note => 'PayUp'})
    redirect_to bets_path
  end
  def index
    @bets = Bet.all
   
  end
  def show
    @bet = Bet.find(params[:id])
  end

  def new
    @bet = Bet.new
    # @user= User.find(params[:id])
    @user = @current_user_id
   
     
    
  end

  def create
    @user = @current_user_id
    @bet = Bet.new(params.require(:bet).permit(:challenge,
      :amount,
      :challenger,
      :challengee, :challenge_start, :challenge_end, :venmo_id) )
    if @bet.save
      # render json: @bet, status: :created
      redirect_to bets_path
    end
    
  end

  def destroy
    @bet = Bet.where(params[:id]).first
    @bet.destroy
    redirect_to users_path
  end

 end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		# Present an empty login form
		@user = User.new
		@is_login = true
	end

	def create
		# Find the user that is trying to log in		
		u = User.where(email: params[:user][:email]).first
		if u && u.authenticate(params[:user][:password])
			# Store as a cookie in the users' browser the ID of them,
			# indicating that they are logged in
			session[:user_id] = u.id.to_s
			redirect_to users_path
		else
			# Go back to the login page
			redirect_to new_session_path
		end
	end 

 
	def destroy
		reset_session
		redirect_to new_session_path
	end
end

app/controllers/userbets_controller.rb
class UserbetsController < ApplicationController

  def new
    @userbet = UserBet.new
  end
 
  def create
    @userbet = UserBet.new(params.require(:userbet).permit(:user_id, :bet_id))
    @userbet.user = current_user
  end

  def destroy
    @userbet = UserBet.where(params[:id]).first
    @userbet.destroy
    redirect_to users_path
  end

  private
  def userbet_params
    params.require(:userbet).permit(:user_id, :bet_id)
  end
  
  def get_user
    @user = current_user
    @user = User.where(:id => params[:user_id]).first
  end
end	 

app/controllers/users_controller.rb
class UsersController < ApplicationController

  respond_to :json

  # def fetch_user
  #   @user = User.find_by_id(params[:id])
  # end


<<<<<<< HEAD
 

  def bet
    @email = params[:email]
    @amount = params[:amount]
    @access_token = params[:access_token]
    url = "https://api.venmo.com/v1/payments"
    @amount = HTTParty.post(url, :query => { "access_token" => @access_token, :email => @email, :amount => @amount, :note => 'PayUp'})
    puts @amount

    render new_user_path
  end

  def new
    if params["code"] 
      auth_code = params["code"]
    end
      url = "https://api.venmo.com/v1/oauth/access_token"
      response = HTTParty.post(url, :query => {
        :client_id => '1917', 
        :client_secret => 'bevp84EhbeJNt39mb6GgFA96jxCJ7Ata', 
        :code => auth_code})
      user = response["user"]
      @userid = user["id"]
      @access_token = response["access_token"]
      refresh_token = response["refresh_token"]
      friends = "https://api.venmo.com/v1/users/" + @userid + "/friends?"
      @retfriend = HTTParty.get(friends, :query => { "access_token" => @access_token})
      @data = @retfriend["data"]
      @user = User.new(:username => user["username"], 
        :first_name => user["first_name"], 
        :last_name => user["last_name"], 
        :display_name => user["display_name"], 
        :is_friend => user["is_friend"], 
        :friends_count => user["friends_count"], 
        :about => response["access_token"], 
        :email => user["email"], 
        :phone => user["phone"], 
        :profile_picture_url => user["profile_picture_url"], 
        :friend_request => user["friend_request"], 
        :trust_request => user["trust_request"], 
        :venmo_id => user["id"], 
        :date_joined => user["date_joined"] )
=======

  def index
    @users = User.all
  end

  def new
    # render :json => {:success => true, info: :info} # on success
    if params["code"]
      auth_code = params["code"]
    end 
    url = "https://api.venmo.com/v1/oauth/access_token"
    @response = HTTParty.post(url, :query => {:client_id => '1917', :client_secret => 'bevp84EhbeJNt39mb6GgFA96jxCJ7Ata', :code => auth_code})
    user = @response["user"]
    @access_token = @response["access_token"]
    @refresh_token = @response["refresh_token"]
    @id = user["id"]

    friends = "https://api.venmo.com/v1/users/" + user["id"] + "/friends?"
    @retfriend = HTTParty.get(friends, :query => { "access_token" => @access_token})
    @data = @retfriend["data"]

    @user = User.new(:username => user["username"], 
      :first_name => user["first_name"], 
      :last_name => user["last_name"], 
      :display_name => user["display_name"], 
      :is_friend => user["is_friend"], 
      :friends_count => user["friends_count"], 
      :about => @response["access_token"], 
      :email => user["email"], 
      :phone => user["phone"], 
      :profile_picture_url => user["profile_picture_url"], 
      :friend_request => user["friend_request"], 
      :trust_request => user["trust_request"], 
      :venmo_id => user["id"], 
      :date_joined => user["date_joined"] )
    
>>>>>>> 621f83c2b1c13f326b9a39dcd2f413e9da282a43
    if @user.save

      @current_user_id = @user.venmo_id
      puts @current_user_id
      redirect_to bets_path

    end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_path
    else
      render :new
    end
  end
<<<<<<< HEAD
=======

  def show
    respond_with User.find(params[:id])
  end

end

  

>>>>>>> 621f83c2b1c13f326b9a39dcd2f413e9da282a43
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bets_helper.rb
module BetsHelper
end

app/helpers/userbets_helper.rb
module UserbetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about/index.html.erb
<div class="body"></div>
		<div class="grad"></div>
		<div class="header">
			<div>Pay<span>Up</span></div>
		</div>
		<br>
		<div class="login">
			<br><h1>Sign Up with PayUp</h1>
				<h4>Click Below to Login with 
				<br><br><a href="https://api.venmo.com/v1/oauth/authorize?client_id=1917&scope=make_payments%20access_profile%20access_email%20access_phone%20access_friends%20access_balance&response_type=code"><%= image_tag 'logowhite.png', width: '160px', border_radius: '20px #000000' %></a> 
		</div>
	</div>

app/views/bets/_form.html.erb
<%#= form_tag new_bet_path do  %>
	<%#= hidden_field_tag "challenger", @current_user %>
	<%#= text_field_tag (:challengee) %>
	<%#= text_field_tag(:challenge) %>
	<%#= text_field_tag(:amount) %>
	<%#= submit_tag %>
<%# end %>

app/views/bets/_issued.html.erb
<div class="container">

  <div class="row">
			  <div class="col-md-6 col-md-offset-3">
				<table class="table table-hover">
					<thead>
						<tr>
							<th><div class="challenger">Challenger</th>
							<th><div class="challengee">Challengee</th>
							<th><div class="challenge">Challenge</th>
							<th><div class="collateral">Collateral</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td><img src="<%#= @profile_picture_url %>" alt="..." class="img-circle"><%#= first_name %></td>
							<td><img src="<%= @profile_picture_url %>" alt="..." class="img-circle"><%#= first_name %></td>
							<td><%#= challenge_description %></td>
							<td><%#= wager %>  <span class="label label-success">Just Challenged!</span></td>
						</tr>
						
					</tbody>
				  
				</table>
		</div>
		</div> 
			

	</div>

app/views/bets/_pending.html.erb
<div class="container">

  <div class="row">
			  <div class="col-md-6 col-md-offset-3">
				<table class="table table-hover">
					<thead>
						<tr>
							<th><div class="challenger">Challenger</th>
							<th><div class="challengee">Challengee</th>
							<th><div class="challenge">Challenge</th>
							<th><div class="collateral">Collateral</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td><img src="<%#= @profile_picture_url %>" alt="..." class="img-circle"><%#= first_name %></td>
							<td><img src="<%= @profile_picture_url %>" alt="..." class="img-circle"><%#= first_name %></td>
							<td><%#= challenge_description %></td>
							<td><%#= wager %>  <span class="label label-success">Just Challenged!</span></td>
						</tr>
						
					</tbody>
				  
				</table>
		</div>
		</div> 
			

	</div>

app/views/bets/index.html.erb
<%= render 'layouts/nav' %>

<%= link_to new_bet_path(@current_user_id) do %>
  <button type="button" class="btn btn-default col-md-2 col-md-offset-5">Place A Bet</button>
<% end %>
<%= @current_user_id %>

<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<table class="table table-hover">
			<thead>
				<h3>All Bets</h3>
				<tr>
					<th><div class="challenge">Challenge</th>
					<th><div class="amount">Amount</th>
					<th><div class="challenger">Challenger</th>
					<th><div class="challengee">Challengee</th>
					<th><div class="settle">Settle</th>
				</tr>
			</thead>
			<tbody>
				
			</tbody>
		</table>
	</div>
</div> 
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<table class="table table-hover">
			<thead>
				<h3>Bets Pending</h3>
				<tr>
					<th><div class="challenge">Challenge</th>
					<th><div class="amount">Amount</th>
					<th><div class="challenger">Challenger</th>
					<th><div class="challengee">Challengee</th>
				</tr>
			</thead>
			<tbody>
				<% @bets.with_pending_state.each do |p| %>
				<tr>
					<td><%= p.challenge %></td>
					<td>$<%= p.amount %>0</td>
					<td><%= p.challenger %></td>
					<td><%= p.challengee %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div> 
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<table class="table table-hover">
			<thead>
				<h3>Bets Accepted</h3>
				<tr>
					<th><div class="challenge">Challenge</th>
					<th><div class="amount">Amount</th>
					<th><div class="challenger">Challenger</th>
					<th><div class="challengee">Challengee</th>
				</tr>
			</thead>
			<tbody>
				<% @bets.with_accepted_state.each do |p| %>
				<tr>
					<td><%= p.challenge %></td>
					<td><%= p.amount %></td>
					<td><%= p.challenger %></td>
					<td><%= p.challengee %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<table class="table table-hover">
			<thead>
				<h3>Bets Rejected</h3>
				<tr>
					<th><div class="challenge">Challenge</th>
					<th><div class="amount">Amount</th>
					<th><div class="challenger">Challenger</th>
					<th><div class="challengee">Challengee</th>
				</tr>
			</thead>
			<tbody>
				<% @bets.with_rejected_state.each do |p| %>
				<tr>
					<td><%= p.challenge %></td>
					<td><%= p.amount %></td>
					<td><%= p.challenger %></td>
					<td><%= p.challengee %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/bets/new.html.erb
<%= render 'layouts/nav' %>

<h1>Create a bet</h1>
<form role="form">
		<%= form_for @bet do |f|  %>

			<div class= "form-group">
				<%=f.text_field :challenge, placeholder: "Challenge description" , class: "form-control" %>
			</div>

			<div class= "form-group">
				<%=f.text_field :amount, placeholder: "Amount" , class: "form-control" %>
			</div>

			<div class= "form-group">
				<%=f.text_field :amount, placeholder: "Amount" , class: "form-control" %>
			</div>

			<div class= "form-group">
				<%=f.text_field :challenger, placeholder: "Challenger" , class: "form-control" %>
			</div>

			 <p>Challengee</p><%= f.collection_select :challengee, User.all, :venmo_id, :display_name, {prompt: "Select a friend"}, {class: "form-control"} %>
			<div class= "form-group">
			 <p>Challenge Start:</p><%=f.date_field :challenge_start %>
			</div>
			<div class= "form-group">
			 <p>Challenge Settlement(End):</p><%=f.date_field :challenge_end %>
			</div>
			
			
			<div class= "form-group">
				<%= f.submit "go!" %>
				<% end %>
			</div>

		<%=  @current_user_id %>
	 </div>
	</div>

app/views/bets/show.html.erb
<%= render 'layouts/nav' %>

<h1><%= @bet.challenger %> bet
<%= @bet.challengee %> 
<%= @bet.amount %>  bucks to 
<%= @bet.challenge %>



<h1><%= @bet.challengee %> Won Settle the bet by paying cash with our app



<h1><%= @bet.challenger %> won and doesn't owe you anything</h1>


<h1>Settle this bet</h1>

<a class="venmo-pay-button" data-recipient-id=<%= @bet.challengee %> data-amount=<%= @bet.amount %> data-note=<%= @bet.challenge %>></a>

app/views/layouts/_challenger.html.erb
<!-- Button trigger modal -->
<button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Make a New Bet!
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Hi {{Logged in User}}</h4>
      </div>
      <div class="modal-body">
       
        <div class="dropdown">
          <a data-toggle="dropdown" href="#">Pick a friend to bet!</a>
          <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
            {{collectionselect}}
          </ul>
        </div>
        Legal Notice Here --->
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Backout(sissy)</button>
        <button type="button" class="btn btn-primary">Send bet</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="navbar1 container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <a class="navbar-brand" href="#">
        <%= image_tag 'handshake1.jpg', width: '30px' %>PayUp
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

      </ul>

      <ul class="nav navbar-nav navbar-right">


        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
         Current User
          <span class="caret"></span>
        </a>
          <ul class="dropdown-menu" role="menu">
            <li>
              <%= link_to 'Log me out', session_path, method: :delete %>
            </li>
            
          </ul>
        </li>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  	<title>PayUp</title>
	<%= stylesheet_link_tag    "application", media: "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	  <script src='https://platform.venmo.com/sdk.js'></script>

</head>
<body>
	<div class="container">

		<%= yield %>
	
	</div>

</body>
</html>

app/views/userbets/new.html.erb
new.html.erb

app/views/users/edit.html.erb
edit.html.erb

app/views/users/index.html.erb
<%= render 'layouts/nav' %>

<div class="body"></div>
		<div class="grad"></div>
		<div class="header">
			<div>Pay<span>Up</span></div>
		</div>
		<br>
		<div class="login">
			<br><h1>Sign Up with PayUp</h1>
				<h4>Click Below to Login with 
				<br><br><a href="https://api.venmo.com/v1/oauth/authorize?client_id=1917&scope=make_payments%20access_profile%20access_email%20access_phone%20access_friends%20access_balance&response_type=code"><%= image_tag 'logowhite.png', width: '160px', border_radius: '20px #000000' %></a> 
		</div>
	</div>

app/views/users/new.html.erb
<%= render 'layouts/nav' %>
<%= render 'layouts/challenger' %>
<%= render 'bets/form' %>


	
<div class="container">
 <%= @data %>
  <div class="row">
			  <div class="col-md-6 col-md-offset-3">
			  	<%= form_tag users_bet_path do  %>
	<%= hidden_field_tag "access_token", @access_token %>
	<%= text_field_tag(:email) %>
	<%= text_field_tag(:amount) %>
	<%= submit_tag %>
<% end %>
				<table class="table table-hover">
					<thead>
						<tr>
							<th><div class="challenger">Challenger</th>
							<th><div class="challengee">Challengee</th>
							<th><div class="challenge">Challenge</th>
							<th><div class="collateral">Collateral</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td><img src="<%#= @profile_picture_url %>" alt="..." class="img-circle"><%#= first_name %></td>
							<td><img src="<%= @profile_picture_url %>" alt="..." class="img-circle"><%#= first_name %></td>
							<td><%#= challenge_description %></td>
							<td><%#= wager %>  <span class="label label-success">Just Challenged!</span></td>
						</tr>
						
					</tbody>
				  
				</table>
		</div>
		</div> 
			

	</div>
<% @data.each do |e| %>
<%= e %></br>
<% end %>


<h1>Make a new bet</h1>
<%= link_to "index", new_bet_path(@current_user_id) %>
<%= @current_user_id %>

<!-- <h1>This is where your fake internet friends should appear</h1> -->



	
	

app/views/users/show.html.erb
<%= render 'layouts/nav' %>
<h1>Hi, <%= current_user.name %>! :)</h1>